In [177]:
import tabula

In [206]:
df = tabula.read_pdf("schedule.pdf", pages='all')
newdf = df.loc[df["Course Abbr"] == "PETE 503"]
x = newdf["Cap"]
x.item()

25.0

In [190]:
newdf = df2.loc[df2["Course Abbr"] != "NaN"]
newdf

,Course Abbr,S/T,Course Title,Cr(US),Cr(ECTS),Start Date,End Date,Days,Time,Enr,Cap,Faculty,Room
0,NaN,NaN,Management,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.322 -
1,MINE 601,1Lb,NaN,3.0,6.0,12-AUG-19,22-NOV-19,T,12:00 PM-01:55 PM,2.0,20.0,Sergei Sabanov,NaN
2,NaN,NaN,and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cap:28
3,NaN,NaN,Sustainability,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Mine Automation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.322 -
6,MINE 602,1Lb,and,3.0,6.0,12-AUG-19,22-NOV-19,W,12:00 PM-01:55 PM,2.0,20.0,Sergei Sabanov,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cap:28
8,NaN,NaN,Maintenance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,Multivariate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nasser,6.322 -
10,MINE 603,1Lb,NaN,3.0,6.0,12-AUG-19,22-NOV-19,R,05:00 PM-06:55 PM,0.0,20.0,NaN,NaN
11,NaN,NaN,Geostatistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madaniesfahani,cap:28
12,NaN,NaN,Underground,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniyar,NaN
13,NaN,NaN,Hard Rock,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Malgazhdar,",6.322 -
14,MINE 606,1L,NaN,3.0,6.0,12-AUG-19,22-NOV-19,F,10:00 AM-12:55 PM,2.0,20.0,NaN,NaN
15,NaN,NaN,Geotechnical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fidelis,cap:28
16,NaN,NaN,Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suorineni,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniyar,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Malgazhdar,",NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.302 -
20,MINE 690,1S,Thesis I,6.0,12.0,12-AUG-19,22-NOV-19,S,09:00 AM-05:00 PM,2.0,20.0,"Saffet Yagiz,",NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cap:48
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fidelis,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Suorineni,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.402 -
25,MINE 700,1S,Thesis Research,0.0,0.0,12-AUG-19,22-NOV-19,S,03:00 PM-06:00 PM,2.0,25.0,TBA TBA,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cap:24
27,NaN,NaN,Advanced Mine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Amoussou Coffi,6.302 -
28,MINE 701,1L,NaN,4.0,8.0,12-AUG-19,22-NOV-19,W,02:00 PM-05:00 PM,0.0,30.0,NaN,NaN
29,NaN,NaN,Geomechanics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adoko,cap:48
30,MINE 601,1L,NaN,3.0,6.0,12-AUG-19,22-NOV-19,T,09:00 AM-11:55 AM,2.0,20.0,Sergei Sabanov,NaN
31,NaN,NaN,and,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cap:24

In [140]:
newdf = newdf.loc[newdf["S/T"] == "1L"]
newdf.size
newdf

,Course Abbr,S/T,Course Title,Cr(US),Cr(ECTS),Start Date,End Date,Days,Time,Enr,Cap,Faculty,Room
2,GEOL 202,1L,Geologic Maps &\rCross-Sections,3.0,6,12-AUG-19,22-NOV-19,T,09:00 AM-09:55 AM,10,20,"Laurent\rRichard,\rMilovan Fustic",6.327 -\rcap:30

In [141]:
from glob import glob
import pandas as pd

In [142]:
pages = glob("schedulepages/*.pdf")
pages.sort()

In [148]:
course = "MINE 603"
lecture = "1L"
df = None
for page in pages:
    currentdf = tabula.read_pdf(page)
    df = pd.concat([df, currentdf])
    print(page)
    newdf = df.loc[df["Course Abbr"] == course]
    if newdf.size == 0: 
        print("Course was not found")
        continue
    print(newdf.size)
    newdf = newdf.loc[newdf["S/T"] == lecture]
    if newdf.size == 0:
        print("Lecture was not found")
        continue
    print(newdf["Cap"])
    break

schedulepages/schedule_1.pdf
Course was not found

FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.
 [ipykernel_launcher.py:6]

schedulepages/schedule_2.pdf
Course was not found

FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.
 [ipykernel_launcher.py:6]

schedulepages/schedule_3.pdf
Course was not found
schedulepages/schedule_4.pdf
Course was not found

FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.
 [ipykernel_launcher.py:6]